### ISSUE TITLE
Cannot load word2vec embeddings

### ISSUE THREAD

**Issue by wbogud** [zenanz/ChemPatentEmbeddings#1]
When I try to load the word2vec embeddings via gensim 3.8.0, I get the error `ModuleNotFoundError: No module named 'w2v'`. Here is the code I use for loading:

```python
from gensim.models import Word2Vec
model = Word2Vec.load("patent_w2v.bin")
```

**Comment by zenanz** [comment]
Sorry for the late reply. The issue is caused by my modification in gensim. Please find the word vectors in .txt format in README.
