### ISSUE TITLE
Unusable embeddings

### ISSUE THREAD

**Issue by Mahmedturk** [zenanz/ChemPatentEmbeddings#3]
Hi,

Both of the embeddings given in this repo are unusable. The word2vec.bin cannot be converted to text.
And ELMo cannot be used, I get the following error while using it,.
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zenanz** [comment]
Duplicate of #1 . We've put them on server for public access.
